name: skewd-env
channels:
  - conda-forge
dependencies:
  - python==3.11.5
  - numpy==1.26.4
  - matplotlib
  - pandas
  - scikit-learn
  - scipy
  - statsmodels
  - gin-config
  - ipykernel
  - pillow==10.1.0
  - tqdm
  - cmaes
  - scikit-optimize
  - pytest
  - cdt
  - graphviz
  - pathos
  - pip
  - rpy2
  - pip:
      - graphical_models
      - python-igraph
      - causal-learn
      - torch --index-url https://download.pytorch.org/whl/cpu